UIMS系统更新了，原来的已经无法使用，稍微改了一下
EugeneJie/AutoEvaluate pull request #2
Opened 2020-12-14 06:01 UTC by ForeverOpp

- 修复 需要验证码登陆 问题
- 修复 登陆表单变更 问题
- 修复 评教表单变更 问题
----
另外，这个填表的表单好像可以做成每次获取的，这样就不用每年都抓一次包了（问题数量等变化）。
谢谢大佬通过PR。

2020-12-14 06:07 UTC, ForeverOpp reviewed
大多数都是IDE自动格式化代码，我只改了33、34、53-57、65、63-64、74和169-183.

2020-12-15 06:34 UTC, EugeneJie requested changes
感谢你对本项目的维护和贡献，因本人已毕业离校无法进行验证，请确保代码运行正常并根据建议修改相关代码后重新提交，再次感谢！

2020-12-15 06:34 UTC, EugeneJie commented on AutoEvaluate.py
> +print(info)
这里应该是调试时的打印信息，需要去掉

2020-12-15 06:34 UTC, EugeneJie commented on AutoEvaluate.py
> +    print(json.loads(s.post(post_url, data=json.dumps(post_data), headers=headers).text)['msg'])
这里打印出来的是什么信息？若非必要信息建议尽量精简

2020-12-15 06:54 UTC, EugeneJie commented
至于表单的问题，由于每年的问题都基本一致，且问题修改具有不确定性（如问题类型、好评选项等），出于谨慎考虑，代码中并未做相关的处理。最后我不是大佬哈，你也可以在代码的Author中加上你的大名并推荐给小伙伴们哦~

2020-12-15 07:25 UTC, ForeverOpp commented on AutoEvaluate.py
> +    print(json.loads(s.post(post_url, data=json.dumps(post_data), headers=headers).text)['msg'])
这个出错会输出错误信息，不过没什么用，主要还是调试用。

2020-12-15 07:26 UTC, ForeverOpp commented
您太客气了，我今年用的时候顺手改了一下。加名字就不必了。

2020-12-15 07:26 UTC, ForeverOpp commented
代码已经改了，在我这里是可以正常运行的。

2020-12-15 07:43 UTC, merged